#version 450

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer buf
{
  float input_data[];
};

layout(std430, binding = 1) buffer buf1
{
  float output_data[];
};

struct UniformData
{
  uint mul;
  uint times;
  uint val[62];
};

layout(binding = 2) uniform buf2
{
  UniformData global_data;
};

void main()
{
  output_data[gl_GlobalInvocationID.y + gl_GlobalInvocationID.x] = input_data[gl_GlobalInvocationID.y + gl_GlobalInvocationID.x] * global_data.mul;
}